### ISSUE TITLE
Add a note about `--alias` parameter

### ISSUE THREAD

**Issue by Pavel910** [webiny/docs.webiny.com#12]
We can selectively deploy components using `--alias=xyz` parameter(s). Add a note to `Development principles` mentioning this parameter.

**Comment by ng29** [comment]
hey @Pavel910 

Can i cater this, more info about this will be required..

**Comment by Pavel910** [comment]
@ng29 This one is so old, it's already outdated. We removed that flag from our current deploy process. Closing this :)
