### ISSUE TITLE
AWS Guide - Placement of .aws folder

### ISSUE THREAD

**Issue by SvenAlHamad** [webiny/docs.webiny.com#149]
Several users got confused in the AWS guide on where to place the `.aws` folder. At the moment there are 2 pitfalls that we identified: 
1. Several users added this to their webiny project folder, instead of the home folder
2. The guide at the moment doesn't cater for windows users - we need to either add a note that they shouldn't be using CMD, or provide windows-based paths.

**Comment by ng29** [comment]
Hey @SvenAlHamad 
Can i place this in my oven ??

**Comment by SvenAlHamad** [comment]
An oven won't work, but in case you wish to contribute, let me know and I'll assign this task to you.

**Comment by ng29** [comment]
@SvenAlHamad  is that so, then we can grill it as i have started AWS recently and will be glad to have hands on

Can i get more insight of this issue ? 

Cheers

**Comment by SvenAlHamad** [comment]
That's great @ng29.

So this issue is about adding additional clarity regarding how to setup AWS profile on Windows environments. This article here is the one that you would need to modify: https://docs.webiny.com/docs/guides/get-started/aws-credentials

At the bottom of that page you'll find a reference to this folder `~/.aws/credentials`. The problem is that Windows users get confused about this as this is a UNIX path. We need to add an info box with a note that on windows the path should be somewhat different, i.e. c:\username\.... 

You can use this article as a reference: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html

**Comment by ng29** [comment]
Heya @SvenAlHamad , apologies for the delay in responding... 

Just checked both docs and inferred that C:\Users\USERNAME\.aws\credentials  this needs to be appended as a note in this doc for window user's safety, cool ?? 

Is there any proper format in which it is best suitable, do let me know. 


Cheers.

**Comment by SvenAlHamad** [comment]
Hey @ng29 - I just left the comment in your PR regarding this change.

**Comment by ng29** [comment]
> Hey @ng29 - I just left the comment in your PR regarding this change.

Hiya @SvenAlHamad , i misssed that while making PR last night.. Has been modified , kindly review and merge 👍 

Cheers

**Comment by SvenAlHamad** [comment]
PR merged - thanks @ng29!
