### ISSUE TITLE
Add a note about "Heap out of memory"

### ISSUE THREAD

**Issue by Pavel910** [webiny/docs.webiny.com#17]
Some users reported the following error during `admin` app build: `Allocation failed - JavaScript heap out of memory`.

This is not something we can solve ourselves, but a solution is to increase the amount of memory available to node process, by settings:

`NODE_OPTIONS=--max_old_space_size=4096`

**Comment by ng29** [comment]
hey @Pavel910 

can i help in this. ?

**Comment by Pavel910** [comment]
@ng29 I don't think it's no longer an issue. No one has reported it for almost a year. Thanks for bringing my attention to it, will close it.
