### ISSUE TITLE
The resources.js config description in https://docs.webiny.com/docs/deep-dive/stacks#resourcesjs is unclear

### ISSUE THREAD

**Issue by markwilcox** [webiny/docs.webiny.com#175]
At the bottom of this section:
https://docs.webiny.com/docs/deep-dive/stacks#resourcesjs
it says:

> With this, we defined 3 resources that will be deployed to your AWS account: a Lambda function, an API Gateway and a CloudFront CDN distribution. Each resource must include the deploy definition, so the deploy process knows what to deploy to AWS.

But in the code the only one that explicitly includes a deploy property is the Lambda function. The other two look like they only have a deploy property, but it isn't named. Is this a default if there's a component specified, or is there some other mechanism here?

If including the extra level (e.g. having an explicit deploy property only for the API Gateway and CDN) works then I'd suggest including it in the example code, and possibly even deprecating and eventually removing the ability to exclude it from the config parsing code. Allowing the same config properties to exist at multiple levels in your object hierarchy can be a source of hard to track-down bugs in a large and complex config.

**Comment by Ashu96** [comment]
@markwilcox Thanks for providing feedback and reporting this issue :+1:
