### ISSUE TITLE
Quick Start minimum node version isn't high enough

### ISSUE THREAD

**Issue by markwilcox** [webiny/docs.webiny.com#176]
The Quick Start (https://docs.webiny.com/docs/get-started/quick-start) says we need version 10.14.0 or greater of node, but if you install that version creating a new project fails because the version of jest being used now requires at least node version 10.14.2.

**Comment by markwilcox** [comment]
Checked out the latest source today to work on a package and the minimum node version is now up to 10.19.0 because of the minimum version of the "got" dependency. Assuming you're not pinning dependencies, perhaps it'd be better to just say node 12.x and "it may work with earlier versions but this is not regularly tested" or something similar?

**Comment by Pavel910** [comment]
@markwilcox That's a good idea, yes. Things are changing fast :D

**Comment by markwilcox** [comment]
I updated the PR.
