### ISSUE TITLE
Instructions to run the website in local machine is not correct and module information is not added in package.json

### ISSUE THREAD

**Issue by sparkingdark** [webiny/docs.webiny.com#200]
I forked the repo and cloned to my local machine.After executing the following commands as per readme.md

```
cd docs.webiny.com
npm install
npm start
```
I got this errors 

```
[debo@localhost docs.webiny.com]$ npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/debo/.npm/_logs/2020-10-04T11_44_41_685Z-debug.log
[debo@localhost docs.webiny.com]$ 
```
Possibly it has no start script information added in  the package.json file and also another error you can face in the
`/docs.webiny.com/website/src` there required node module information is not added to the main package.json file.
I need to rum `npm install` again to get all the modules installed and after that in this directory `/docs.webiny.com/website/src`
```npm start``` worked fine and website running.

so possible solution:
- Edit the readme.md file instructions for runing in local enviorment for now.

Later work:
- Edit the package.json file with npm modules description
- adding the start script in main package.json so the website can be start from local enviourment .

**Comment by sparkingdark** [comment]
I started working on it.

**Comment by Ashu96** [comment]
> I forked the repo and cloned to my local machine.After executing the following commands as per readme.md
> 
> ```
> cd docs.webiny.com
> npm install
> npm start
> ```
> 
> I got this errors
> 
> ```
> [debo@localhost docs.webiny.com]$ npm start
> npm ERR! missing script: start
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/debo/.npm/_logs/2020-10-04T11_44_41_685Z-debug.log
> [debo@localhost docs.webiny.com]$ 
> ```
> 
> Possibly it has no start script information added in the package.json file and also another error you can face in the
> `/docs.webiny.com/website/src` there required node module information is not added to the main package.json file.
> I need to rum `npm install` again to get all the modules installed and after that in this directory `/docs.webiny.com/website/src`
> `npm start` worked fine and website running.
> 
> so possible solution:
> 
> * Edit the readme.md file instructions for runing in local enviorment for now.
> 
> Later work:
> 
> * Edit the package.json file with npm modules description
> * adding the start script in main package.json so the website can be start from local enviourment .

@sparkingdark It's mentioned in the README file to do
`cd docs.webiny.com/website` while you used `cd docs.webiny.com` which will fail of course. I would suggest you to please take another look at the README file :slightly_smiling_face: 

On this note, I'm closing the issue.
