### ISSUE TITLE
News website

### ISSUE THREAD

**Issue by zherar7ordoya** [webiny/docs.webiny.com#220]
Hi. I'm reading the documentation and mulling over the issue, but I can't "put the pieces together" to build a conventional news website, where there are well-differentiated actors: the "outsider" reader, the reader with an account, the journalist, the editor-in-chief (who authorizes the publication of the article made by the journalist) and the developer (all with their own accounts but different roles, and therefore with different screens: for example, that a journalist can access the editor online, and obviously a reader cannot do it). I don't know if this already exists but documentation is sparse on these features, or these functions are not in webiny yet and need to be added, or if webiny is already ready for that (and an accompanying example and documentation would be helpful). That is why I put this request in all three places. Sorry if I shouldn't have done it like that. Thank you for your time and for your wonderful project.

**Comment by Pavel910** [comment]
Hey @zherar7ordoya, there's nothing wrong with the issue, no worries 🍻 

In v4 (current officially published version), your scenario is very difficult to achieve. But, v5 beta will be released some time next week, where a lot of this stuff is already built-in, and the things that are not built-in are easy to achieve. I strongly recommend you wait a couple more days, and try the v5 version. Once you see all the features we have there, you can then see if there's something custom you need to develop, and we can then go from there and update the docs with examples etc.

Btw. current docs are very sparse indeed; we're now working on the docs for v5, they will also be published next week, but they're still  work in progress.

Please join our Slack community at https://www.webiny.com/slack and we can chat there; somebody from the team is always available there to help you out.

**Comment by zherar7ordoya** [comment]
Thanks for your kind reply.
