### ISSUE TITLE
Admin page keeps on loading

### ISSUE THREAD

**Issue by Sudharshan1409** [webiny/docs.webiny.com#252]
After Admin Sign-in, the page keeps on loading. Tried several times and same result

![image](https://user-images.githubusercontent.com/41262261/111409215-83707d00-86fc-11eb-9148-e60ac495e5a0.png)

**Comment by brunozoric** [comment]
Hi @Sudharshan1409.
Can you check if there are any console or network errors and c/p them here if any?

thanks

**Comment by Sudharshan1409** [comment]
Sure I'll do that
