### ISSUE TITLE
Fix wrong command reference in docs

### ISSUE THREAD

**Issue by xintellion** [webiny/docs.webiny.com#289]
docs/tutorials/create-an-application/introduction.mdx

replace:
`yarn link-packages`
with 
`yarn link-workspaces`

https://github.com/webiny/webiny-js/blob/ee5733e3bb9dca066600141516a3607a07eb38b5/packages/cwp-template-aws/template/dependencies.json

**Comment by doitadrian** [comment]
Closing this as this tutorial will get completely replaced in the following days.
