### ISSUE TITLE
Typo on the writers programs page. I assume you mean Angels and not Angles. 

### ISSUE THREAD

**Issue by varun-singh-01** [webiny/docs.webiny.com#530]
![image](https://user-images.githubusercontent.com/42174119/203810021-24b0427d-9366-4e9d-ac30-92d7392389cb.png)

I was going through your writers program page and found a typo. Not a major thing, but something we can keep in the end to correct.

**Comment by endymion1818** [comment]
Hi @varun-singh-01, thanks so much for this issue, actually we did mean to put "angles", because we are looking for different vectors of technical tools to engage authors on. We don't really mind whether they are corporeal or not.

**Comment by varun-singh-01** [comment]
Ok Then, I shall close this issue then. Thanks for your response.

**Comment by endymion1818** [comment]
Thanks for your contribution Varun, and please tell us if you find anything else like this, we're always happy to improve and correct our mistakes.
