### ISSUE TITLE
Update https://docs.webiny.com/docs/webiny-apps/security/development/app/components/

### ISSUE THREAD

**Issue by EmilK15** [webiny/docs.webiny.com#64]
Double check to see if SecureRoute and SecureView are both necessary.

**Comment by doitadrian** [comment]
Not sure what you were aiming at here but both components are very necessary. 🙂

**Comment by Pavel910** [comment]
Actually it was me aiming at it :D Those components are 90% the same, so I was wondering if we can get away with making it into 1 component. If it's really necessary to have 2 components, let's leave it as is. 

But, do we need to have `roles` prop?

**Comment by doitadrian** [comment]
Roles - no.

Those are completely removed, only scopes are relevant now.

**Comment by doitadrian** [comment]
Regarding components, if you ask me, I would it components as-is. `SecureRoute`, as you've probably seen, will render a not-authorized error message, which can be customized via a plugin. With it, you only wrap the route, and fallback render happens automatically, no need to handle it for every route.

And `SecureView` is just for rendering/not-rendering parts of the UI. We use it in menus components for example, to render/not-render menu items accordingly.

**Comment by doitadrian** [comment]
BTW guys, there is this PR that removes usage of `roles` prop in the docs articles:

https://github.com/webiny/docs.webiny.com/pull/31

I can merge into `next` branch.

**Comment by Pavel910** [comment]
That would be nice 👍

**Comment by doitadrian** [comment]
Although, I noticed a few things here that are incorrect (didn't do a review after final changes were made).

Anyways, I'll take a look and merge it.

**Comment by doitadrian** [comment]
ℹ️ Merged (`next` branch) and fixed content in the following articles:

- /docs/webiny-apps/security/development/app/components/secure-view
- /docs/webiny-apps/security/development/app/components/secure-route
- /docs/webiny-apps/security/development/api/graphql-helpers/has-scope

**Comment by EmilK15** [comment]
Adrian already resolved this issue, so I'll close this.
