### ISSUE TITLE
Setup Netlify build for "next" branch

### ISSUE THREAD

**Issue by Pavel910** [webiny/docs.webiny.com#66]

**Comment by Ashu96** [comment]
If by `Netlify` build you mean the preview URL for every PR made against `next` branch than I think it's working because you have set up the pipeline :smile_cat: 

![image](https://user-images.githubusercontent.com/13612227/81812800-41a70100-9544-11ea-9d04-d5f2888b8d2a.png)

**Comment by Pavel910** [comment]
Right, closing this one 🚀
