### ISSUE TITLE
Update admin app plugin reference

### ISSUE THREAD

**Issue by Pavel910** [webiny/docs.webiny.com#69]
I updated our `app-admin` package in a way that plugin types (both TS and actual plugin `type` field) now include the `admin-` prefix. It helps with autocomplete and also creates kind of a `namespace` for plugins within admin app.

We will need to update `Admin` app section of the docs to include this change:
![image](https://user-images.githubusercontent.com/3920893/81594239-dda7ff80-93c0-11ea-8c2b-5143a84e0b22.png)

**Comment by Ashu96** [comment]
We also need to update plugin reference link in the source code `packages/app-admin/src/types.ts`
For example:
https://docs.webiny.com/docs/webiny-apps/admin/development/plugins-reference/app#header-left 
will become 
https://docs.webiny.com/docs/webiny-apps/admin/development/plugins-reference/app#admin-header-left
