### ISSUE TITLE
Update AWS credentials setup instructions

### ISSUE THREAD

**Issue by Pavel910** [webiny/docs.webiny.com#78]
In this article: https://docs.webiny.com/docs/get-started/quick-start we should remove the link to Youtube for AWS setup, as it is confusing people. It references SLS framework, and we don't use it.

![image](https://user-images.githubusercontent.com/3920893/81779108-53f94e80-94f4-11ea-86b4-fbe7f23ad367.png)

Instead it's best to point users to AWS docs on configuring credentials:
https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-credentials.html

**Comment by Fsalker** [comment]
also mention that an iam user needs to be created, so that you have the `aws_access_key_id` and `aws_secret_access_key` mentioned in aws' docs
