### ISSUE TITLE
Update Getting Started to include change to add AWS credentials

### ISSUE THREAD

**Issue by EmilK15** [webiny/docs.webiny.com#87]
We removed aws credentials from .env.json files into the global config in ~./aws/credentials . 
Include this step in the Getting Started or where it is relevant in the documentation.

**Comment by Pavel910** [comment]
Actually we didn’t move the credentials there, we just don’t need to know how the user is setting up his credentials. The credentials file is the most common for day to day use, but enterprises would have it differently, so in the article it’s good to mention that there are several ways to configure this (there is a guide in AWS docs).

As long as AWS SDK can figure out your identity, Webiny will be happy no matter how you configure your credentials.
